// Code generated by protoc-gen-go-cgrpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-cgrpc v0.0.141
// 	protoc              v7.34.0
// source: api/account_money.proto

package api

import (
	context "context"
	cerror "github.com/chenjie199234/Corelib/cerror"
	cgrpc "github.com/chenjie199234/Corelib/cgrpc"
	grpc "google.golang.org/grpc"
	slog "log/slog"
)

var _CGrpcPathMoneyGetMoneyLogs = "/account.Money/GetMoneyLogs"

type MoneyCGrpcClient interface {
	GetMoneyLogs(context.Context, *GetMoneyLogsReq) (*GetMoneyLogsResp, error)
}

type moneyCGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneyCGrpcClient(cc grpc.ClientConnInterface) MoneyCGrpcClient {
	return &moneyCGrpcClient{cc: cc}
}

func (c *moneyCGrpcClient) GetMoneyLogs(ctx context.Context, req *GetMoneyLogsReq) (*GetMoneyLogsResp, error) {
	if req == nil {
		return nil, cerror.ErrReq
	}
	if errstr := req.Validate(); errstr != "" {
		slog.ErrorContext(ctx, "[/account.Money/GetMoneyLogs] request validate failed", slog.String("error", errstr))
		return nil, cerror.ErrReq
	}
	resp := new(GetMoneyLogsResp)
	if e := c.cc.Invoke(ctx, _CGrpcPathMoneyGetMoneyLogs, req, resp); e != nil {
		slog.ErrorContext(ctx, "[/account.Money/GetMoneyLogs] invoke failed", slog.String("error", e.Error()))
		return nil, e
	}
	return resp, nil
}

type MoneyCGrpcServer interface {
	// Context is cgrpc.NoStreamServerContext
	GetMoneyLogs(context.Context, *GetMoneyLogsReq) (*GetMoneyLogsResp, error)
}

func _Money_GetMoneyLogs_CGrpcHandler(handler func(context.Context, *GetMoneyLogsReq) (*GetMoneyLogsResp, error)) cgrpc.OutsideHandler {
	return func(ctx *cgrpc.ServerContext) {
		req := new(GetMoneyLogsReq)
		if e := ctx.Recv(req); e != nil {
			slog.ErrorContext(ctx, "[/account.Money/GetMoneyLogs] read request failed", slog.String("error", e.Error()))
			ctx.Abort(cerror.ErrReq)
			return
		}
		if errstr := req.Validate(); errstr != "" {
			slog.ErrorContext(ctx, "[/account.Money/GetMoneyLogs] request validate failed", slog.String("error", errstr))
			ctx.Abort(cerror.ErrReq)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(GetMoneyLogsResp)
		}
		if e := ctx.Send(resp); e != nil {
			slog.ErrorContext(ctx, "[/account.Money/GetMoneyLogs] send response failed", slog.String("error", e.Error()))
		}
	}
}
func RegisterMoneyCGrpcServer(engine *cgrpc.CGrpcServer, svc MoneyCGrpcServer, allmids map[string]cgrpc.OutsideHandler) {
	// avoid lint
	_ = allmids
	engine.RegisterHandler("account.Money", "GetMoneyLogs", false, false, _Money_GetMoneyLogs_CGrpcHandler(svc.GetMoneyLogs))
}
