// Code generated by protoc-gen-go-cgrpc. DO NOT EDIT.
// version:
// 	protoc-gen-go-cgrpc v0.0.111<br />
// 	protoc              v4.25.3<br />
// source: api/account_base.proto<br />

package api

import (
	context "context"
	cerror "github.com/chenjie199234/Corelib/cerror"
	cgrpc "github.com/chenjie199234/Corelib/cgrpc"
	log "github.com/chenjie199234/Corelib/log"
	grpc "google.golang.org/grpc"
)

var _CGrpcPathBaseBaseInfo = "/account.base/base_info"

type BaseCGrpcClient interface {
	BaseInfo(context.Context, *BaseInfoReq, ...grpc.CallOption) (*BaseInfoResp, error)
}

type baseCGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseCGrpcClient(cc grpc.ClientConnInterface) BaseCGrpcClient {
	return &baseCGrpcClient{cc: cc}
}

func (c *baseCGrpcClient) BaseInfo(ctx context.Context, req *BaseInfoReq, opts ...grpc.CallOption) (*BaseInfoResp, error) {
	if req == nil {
		return nil, cerror.ErrReq
	}
	resp := new(BaseInfoResp)
	if e := c.cc.Invoke(ctx, _CGrpcPathBaseBaseInfo, req, resp, opts...); e != nil {
		return nil, e
	}
	return resp, nil
}

type BaseCGrpcServer interface {
	BaseInfo(context.Context, *BaseInfoReq) (*BaseInfoResp, error)
}

func _Base_BaseInfo_CGrpcHandler(handler func(context.Context, *BaseInfoReq) (*BaseInfoResp, error)) cgrpc.OutsideHandler {
	return func(ctx *cgrpc.Context) {
		req := new(BaseInfoReq)
		if e := ctx.DecodeReq(req); e != nil {
			log.Error(ctx, "[/account.base/base_info] decode failed")
			ctx.Abort(cerror.ErrReq)
			return
		}
		if errstr := req.Validate(); errstr != "" {
			log.Error(ctx, "[/account.base/base_info] validate failed", log.String("validate", errstr))
			ctx.Abort(cerror.ErrReq)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(BaseInfoResp)
		}
		ctx.Write(resp)
	}
}
func RegisterBaseCGrpcServer(engine *cgrpc.CGrpcServer, svc BaseCGrpcServer, allmids map[string]cgrpc.OutsideHandler) {
	// avoid lint
	_ = allmids
	{
		requiredMids := []string{"accesskey"}
		mids := make([]cgrpc.OutsideHandler, 0, 2)
		for _, v := range requiredMids {
			if mid, ok := allmids[v]; ok {
				mids = append(mids, mid)
			} else {
				panic("missing midware:" + v)
			}
		}
		mids = append(mids, _Base_BaseInfo_CGrpcHandler(svc.BaseInfo))
		engine.RegisterHandler("account.base", "base_info", mids...)
	}
}
