// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/account_base.proto

//this is the proto package name,all proto in this project must use this name as the proto package name

package api

import (
	_ "github.com/chenjie199234/Corelib/pbex"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Idcard        string                 `protobuf:"bytes,2,opt,name=idcard,proto3" json:"idcard,omitempty"`
	Tel           string                 `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Ctime         uint32                 `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	BindOauths    []string               `protobuf:"bytes,6,rep,name=bind_oauths,json=bindOauths,proto3" json:"bind_oauths,omitempty"`
	Money         map[string]int32       `protobuf:"bytes,7,rep,name=money,proto3" json:"money,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Ban           string                 `protobuf:"bytes,8,opt,name=ban,proto3" json:"ban,omitempty"` //if this is not empty,means this account is banned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_api_account_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{0}
}

func (x *BaseInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BaseInfo) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

func (x *BaseInfo) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *BaseInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BaseInfo) GetCtime() uint32 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *BaseInfo) GetBindOauths() []string {
	if x != nil {
		return x.BindOauths
	}
	return nil
}

func (x *BaseInfo) GetMoney() map[string]int32 {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *BaseInfo) GetBan() string {
	if x != nil {
		return x.Ban
	}
	return ""
}

type BaseInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcType       string                 `protobuf:"bytes,1,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"` //if this is empty,means get self's baseinfo,src_type will force to user_id and the src is from token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoReq) Reset() {
	*x = BaseInfoReq{}
	mi := &file_api_account_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoReq) ProtoMessage() {}

func (x *BaseInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoReq.ProtoReflect.Descriptor instead.
func (*BaseInfoReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfoReq) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *BaseInfoReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

type BaseInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *BaseInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoResp) Reset() {
	*x = BaseInfoResp{}
	mi := &file_api_account_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoResp) ProtoMessage() {}

func (x *BaseInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoResp.ProtoReflect.Descriptor instead.
func (*BaseInfoResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{2}
}

func (x *BaseInfoResp) GetInfo() *BaseInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type BanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcType       string                 `protobuf:"bytes,1,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanReq) Reset() {
	*x = BanReq{}
	mi := &file_api_account_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanReq) ProtoMessage() {}

func (x *BanReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanReq.ProtoReflect.Descriptor instead.
func (*BanReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{3}
}

func (x *BanReq) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *BanReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *BanReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanResp) Reset() {
	*x = BanResp{}
	mi := &file_api_account_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanResp) ProtoMessage() {}

func (x *BanResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanResp.ProtoReflect.Descriptor instead.
func (*BanResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{4}
}

type UnbanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcType       string                 `protobuf:"bytes,1,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanReq) Reset() {
	*x = UnbanReq{}
	mi := &file_api_account_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanReq) ProtoMessage() {}

func (x *UnbanReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanReq.ProtoReflect.Descriptor instead.
func (*UnbanReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{5}
}

func (x *UnbanReq) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *UnbanReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

type UnbanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanResp) Reset() {
	*x = UnbanResp{}
	mi := &file_api_account_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanResp) ProtoMessage() {}

func (x *UnbanResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanResp.ProtoReflect.Descriptor instead.
func (*UnbanResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{6}
}

type GetOauthUrlReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OauthServiceName string                 `protobuf:"bytes,1,opt,name=oauth_service_name,json=oauthServiceName,proto3" json:"oauth_service_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOauthUrlReq) Reset() {
	*x = GetOauthUrlReq{}
	mi := &file_api_account_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOauthUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOauthUrlReq) ProtoMessage() {}

func (x *GetOauthUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOauthUrlReq.ProtoReflect.Descriptor instead.
func (*GetOauthUrlReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{7}
}

func (x *GetOauthUrlReq) GetOauthServiceName() string {
	if x != nil {
		return x.OauthServiceName
	}
	return ""
}

type GetOauthUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOauthUrlResp) Reset() {
	*x = GetOauthUrlResp{}
	mi := &file_api_account_base_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOauthUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOauthUrlResp) ProtoMessage() {}

func (x *GetOauthUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOauthUrlResp.ProtoReflect.Descriptor instead.
func (*GetOauthUrlResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{8}
}

func (x *GetOauthUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LoginReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	SrcType string                 `protobuf:"bytes,1,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	// when src_type is oauth,this is the oauth service name
	SrcTypeExtra string `protobuf:"bytes,2,opt,name=src_type_extra,json=srcTypeExtra,proto3" json:"src_type_extra,omitempty"`
	// when src_type is idcard this can't be dynamic
	// when src_type is oauth,this can't be static
	PasswordType string `protobuf:"bytes,3,opt,name=password_type,json=passwordType,proto3" json:"password_type,omitempty"`
	// when password_type is dynamic and this is empty,means send dynamic password to email or tel.
	// when password_type is dynamic and this is not empty,means verify dynamic password.
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_account_base_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{9}
}

func (x *LoginReq) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *LoginReq) GetSrcTypeExtra() string {
	if x != nil {
		return x.SrcTypeExtra
	}
	return ""
}

func (x *LoginReq) GetPasswordType() string {
	if x != nil {
		return x.PasswordType
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Token       string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Tokenexpire uint64                 `protobuf:"varint,2,opt,name=tokenexpire,proto3" json:"tokenexpire,omitempty"` //unix nano timestamp
	Info        *BaseInfo              `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	//verify:server already send the dynamic password to user's email or tel(depend on the login_req's src_type and src) and is waiting for verify
	//password:login success,but this account is new and it can be setted with a static password(optional)
	//success:nothing need to do
	Step          string `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_api_account_base_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{10}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetTokenexpire() uint64 {
	if x != nil {
		return x.Tokenexpire
	}
	return 0
}

func (x *LoginResp) GetInfo() *BaseInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *LoginResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

type TemporaryTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporaryTokenReq) Reset() {
	*x = TemporaryTokenReq{}
	mi := &file_api_account_base_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporaryTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryTokenReq) ProtoMessage() {}

func (x *TemporaryTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryTokenReq.ProtoReflect.Descriptor instead.
func (*TemporaryTokenReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{11}
}

type TemporaryTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Tokenexpire   uint64                 `protobuf:"varint,2,opt,name=tokenexpire,proto3" json:"tokenexpire,omitempty"` //unix nano timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporaryTokenResp) Reset() {
	*x = TemporaryTokenResp{}
	mi := &file_api_account_base_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporaryTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryTokenResp) ProtoMessage() {}

func (x *TemporaryTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryTokenResp.ProtoReflect.Descriptor instead.
func (*TemporaryTokenResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{12}
}

func (x *TemporaryTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TemporaryTokenResp) GetTokenexpire() uint64 {
	if x != nil {
		return x.Tokenexpire
	}
	return 0
}

type SelfInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfInfoReq) Reset() {
	*x = SelfInfoReq{}
	mi := &file_api_account_base_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfInfoReq) ProtoMessage() {}

func (x *SelfInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfInfoReq.ProtoReflect.Descriptor instead.
func (*SelfInfoReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{13}
}

type SelfInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *BaseInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfInfoResp) Reset() {
	*x = SelfInfoResp{}
	mi := &file_api_account_base_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfInfoResp) ProtoMessage() {}

func (x *SelfInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfInfoResp.ProtoReflect.Descriptor instead.
func (*SelfInfoResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{14}
}

func (x *SelfInfoResp) GetInfo() *BaseInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdateStaticPasswordReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// if this is empty,means this is the first time to set the static password
	OldStaticPassword string `protobuf:"bytes,1,opt,name=old_static_password,json=oldStaticPassword,proto3" json:"old_static_password,omitempty"`
	NewStaticPassword string `protobuf:"bytes,2,opt,name=new_static_password,json=newStaticPassword,proto3" json:"new_static_password,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateStaticPasswordReq) Reset() {
	*x = UpdateStaticPasswordReq{}
	mi := &file_api_account_base_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaticPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaticPasswordReq) ProtoMessage() {}

func (x *UpdateStaticPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaticPasswordReq.ProtoReflect.Descriptor instead.
func (*UpdateStaticPasswordReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateStaticPasswordReq) GetOldStaticPassword() string {
	if x != nil {
		return x.OldStaticPassword
	}
	return ""
}

func (x *UpdateStaticPasswordReq) GetNewStaticPassword() string {
	if x != nil {
		return x.NewStaticPassword
	}
	return ""
}

type UpdateStaticPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaticPasswordResp) Reset() {
	*x = UpdateStaticPasswordResp{}
	mi := &file_api_account_base_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaticPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaticPasswordResp) ProtoMessage() {}

func (x *UpdateStaticPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaticPasswordResp.ProtoReflect.Descriptor instead.
func (*UpdateStaticPasswordResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{16}
}

type ResetStaticPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResetStaticPasswordReq) Reset() {
	*x = ResetStaticPasswordReq{}
	mi := &file_api_account_base_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStaticPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStaticPasswordReq) ProtoMessage() {}

func (x *ResetStaticPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStaticPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetStaticPasswordReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{17}
}

func (x *ResetStaticPasswordReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *ResetStaticPasswordReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *ResetStaticPasswordReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

type ResetStaticPasswordResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the update_oauth_req's verify_src_type) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStaticPasswordResp) Reset() {
	*x = ResetStaticPasswordResp{}
	mi := &file_api_account_base_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStaticPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStaticPasswordResp) ProtoMessage() {}

func (x *ResetStaticPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStaticPasswordResp.ProtoReflect.Descriptor instead.
func (*ResetStaticPasswordResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{18}
}

func (x *ResetStaticPasswordResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ResetStaticPasswordResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type IdcardDuplicateCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idcard        string                 `protobuf:"bytes,1,opt,name=idcard,proto3" json:"idcard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdcardDuplicateCheckReq) Reset() {
	*x = IdcardDuplicateCheckReq{}
	mi := &file_api_account_base_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdcardDuplicateCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdcardDuplicateCheckReq) ProtoMessage() {}

func (x *IdcardDuplicateCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdcardDuplicateCheckReq.ProtoReflect.Descriptor instead.
func (*IdcardDuplicateCheckReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{19}
}

func (x *IdcardDuplicateCheckReq) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

type IdcardDuplicateCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duplicate     bool                   `protobuf:"varint,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdcardDuplicateCheckResp) Reset() {
	*x = IdcardDuplicateCheckResp{}
	mi := &file_api_account_base_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdcardDuplicateCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdcardDuplicateCheckResp) ProtoMessage() {}

func (x *IdcardDuplicateCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdcardDuplicateCheckResp.ProtoReflect.Descriptor instead.
func (*IdcardDuplicateCheckResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{20}
}

func (x *IdcardDuplicateCheckResp) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type SetIdcardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idcard        string                 `protobuf:"bytes,1,opt,name=idcard,proto3" json:"idcard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIdcardReq) Reset() {
	*x = SetIdcardReq{}
	mi := &file_api_account_base_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIdcardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIdcardReq) ProtoMessage() {}

func (x *SetIdcardReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIdcardReq.ProtoReflect.Descriptor instead.
func (*SetIdcardReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{21}
}

func (x *SetIdcardReq) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

type SetIdcardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIdcardResp) Reset() {
	*x = SetIdcardResp{}
	mi := &file_api_account_base_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIdcardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIdcardResp) ProtoMessage() {}

func (x *SetIdcardResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIdcardResp.ProtoReflect.Descriptor instead.
func (*SetIdcardResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{22}
}

type UpdateOauthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	// if verify_dynamic_password is not empty,this should not be empty too
	NewOauthServiceName string `protobuf:"bytes,4,opt,name=new_oauth_service_name,json=newOauthServiceName,proto3" json:"new_oauth_service_name,omitempty"`
	// if verify_dynamic_password is not empty,this should not be empty too
	NewOauthDynamicPassword string `protobuf:"bytes,5,opt,name=new_oauth_dynamic_password,json=newOauthDynamicPassword,proto3" json:"new_oauth_dynamic_password,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateOauthReq) Reset() {
	*x = UpdateOauthReq{}
	mi := &file_api_account_base_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOauthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOauthReq) ProtoMessage() {}

func (x *UpdateOauthReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOauthReq.ProtoReflect.Descriptor instead.
func (*UpdateOauthReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateOauthReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *UpdateOauthReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *UpdateOauthReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

func (x *UpdateOauthReq) GetNewOauthServiceName() string {
	if x != nil {
		return x.NewOauthServiceName
	}
	return ""
}

func (x *UpdateOauthReq) GetNewOauthDynamicPassword() string {
	if x != nil {
		return x.NewOauthDynamicPassword
	}
	return ""
}

type UpdateOauthResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the update_oauth_req's verify_src_type) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOauthResp) Reset() {
	*x = UpdateOauthResp{}
	mi := &file_api_account_base_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOauthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOauthResp) ProtoMessage() {}

func (x *UpdateOauthResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOauthResp.ProtoReflect.Descriptor instead.
func (*UpdateOauthResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateOauthResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *UpdateOauthResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type DelOauthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	DelOauthServiceName   string `protobuf:"bytes,4,opt,name=del_oauth_service_name,json=delOauthServiceName,proto3" json:"del_oauth_service_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DelOauthReq) Reset() {
	*x = DelOauthReq{}
	mi := &file_api_account_base_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOauthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOauthReq) ProtoMessage() {}

func (x *DelOauthReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOauthReq.ProtoReflect.Descriptor instead.
func (*DelOauthReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{25}
}

func (x *DelOauthReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *DelOauthReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *DelOauthReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

func (x *DelOauthReq) GetDelOauthServiceName() string {
	if x != nil {
		return x.DelOauthServiceName
	}
	return ""
}

type DelOauthResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the del_oauth_req's verify_src_type) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// if this is true,means this is the last way to login this account
	// if del this,this account will be deleted completely
	Final bool `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelOauthResp) Reset() {
	*x = DelOauthResp{}
	mi := &file_api_account_base_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOauthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOauthResp) ProtoMessage() {}

func (x *DelOauthResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOauthResp.ProtoReflect.Descriptor instead.
func (*DelOauthResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{26}
}

func (x *DelOauthResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *DelOauthResp) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *DelOauthResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type EmailDuplicateCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailDuplicateCheckReq) Reset() {
	*x = EmailDuplicateCheckReq{}
	mi := &file_api_account_base_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailDuplicateCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailDuplicateCheckReq) ProtoMessage() {}

func (x *EmailDuplicateCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailDuplicateCheckReq.ProtoReflect.Descriptor instead.
func (*EmailDuplicateCheckReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{27}
}

func (x *EmailDuplicateCheckReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailDuplicateCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duplicate     bool                   `protobuf:"varint,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailDuplicateCheckResp) Reset() {
	*x = EmailDuplicateCheckResp{}
	mi := &file_api_account_base_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailDuplicateCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailDuplicateCheckResp) ProtoMessage() {}

func (x *EmailDuplicateCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailDuplicateCheckResp.ProtoReflect.Descriptor instead.
func (*EmailDuplicateCheckResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{28}
}

func (x *EmailDuplicateCheckResp) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type UpdateEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	NewEmail              string `protobuf:"bytes,4,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	// if this is empty,means send dynamic password.
	// if this is not empty,means verify dynamic password.
	NewEmailDynamicPassword string `protobuf:"bytes,5,opt,name=new_email_dynamic_password,json=newEmailDynamicPassword,proto3" json:"new_email_dynamic_password,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateEmailReq) Reset() {
	*x = UpdateEmailReq{}
	mi := &file_api_account_base_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailReq) ProtoMessage() {}

func (x *UpdateEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailReq.ProtoReflect.Descriptor instead.
func (*UpdateEmailReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateEmailReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *UpdateEmailReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *UpdateEmailReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

func (x *UpdateEmailReq) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

func (x *UpdateEmailReq) GetNewEmailDynamicPassword() string {
	if x != nil {
		return x.NewEmailDynamicPassword
	}
	return ""
}

type UpdateEmailResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the update_email_req's verify_src_type) and is waiting for verify
	//newverify:server already send the dynamic password to the new email(depend on the update_email_req's new_email) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailResp) Reset() {
	*x = UpdateEmailResp{}
	mi := &file_api_account_base_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailResp) ProtoMessage() {}

func (x *UpdateEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailResp.ProtoReflect.Descriptor instead.
func (*UpdateEmailResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateEmailResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *UpdateEmailResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type DelEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DelEmailReq) Reset() {
	*x = DelEmailReq{}
	mi := &file_api_account_base_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelEmailReq) ProtoMessage() {}

func (x *DelEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelEmailReq.ProtoReflect.Descriptor instead.
func (*DelEmailReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{31}
}

func (x *DelEmailReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *DelEmailReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *DelEmailReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

type DelEmailResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the del_email_req's verify_src_type) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// if this is true,means this is the last way to login this account
	// if del this,this account will be deleted completely
	Final bool `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelEmailResp) Reset() {
	*x = DelEmailResp{}
	mi := &file_api_account_base_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelEmailResp) ProtoMessage() {}

func (x *DelEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelEmailResp.ProtoReflect.Descriptor instead.
func (*DelEmailResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{32}
}

func (x *DelEmailResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *DelEmailResp) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *DelEmailResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type TelDuplicateCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tel           string                 `protobuf:"bytes,1,opt,name=tel,proto3" json:"tel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelDuplicateCheckReq) Reset() {
	*x = TelDuplicateCheckReq{}
	mi := &file_api_account_base_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelDuplicateCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelDuplicateCheckReq) ProtoMessage() {}

func (x *TelDuplicateCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelDuplicateCheckReq.ProtoReflect.Descriptor instead.
func (*TelDuplicateCheckReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{33}
}

func (x *TelDuplicateCheckReq) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

type TelDuplicateCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duplicate     bool                   `protobuf:"varint,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelDuplicateCheckResp) Reset() {
	*x = TelDuplicateCheckResp{}
	mi := &file_api_account_base_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelDuplicateCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelDuplicateCheckResp) ProtoMessage() {}

func (x *TelDuplicateCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelDuplicateCheckResp.ProtoReflect.Descriptor instead.
func (*TelDuplicateCheckResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{34}
}

func (x *TelDuplicateCheckResp) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type UpdateTelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	NewTel                string `protobuf:"bytes,4,opt,name=new_tel,json=newTel,proto3" json:"new_tel,omitempty"`
	// if this is empty,means send dynamic password.
	// if this is not empty,means verify dynamic password.
	NewTelDynamicPassword string `protobuf:"bytes,5,opt,name=new_tel_dynamic_password,json=newTelDynamicPassword,proto3" json:"new_tel_dynamic_password,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateTelReq) Reset() {
	*x = UpdateTelReq{}
	mi := &file_api_account_base_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTelReq) ProtoMessage() {}

func (x *UpdateTelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTelReq.ProtoReflect.Descriptor instead.
func (*UpdateTelReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateTelReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *UpdateTelReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *UpdateTelReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

func (x *UpdateTelReq) GetNewTel() string {
	if x != nil {
		return x.NewTel
	}
	return ""
}

func (x *UpdateTelReq) GetNewTelDynamicPassword() string {
	if x != nil {
		return x.NewTelDynamicPassword
	}
	return ""
}

type UpdateTelResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the update_tel_req's verify_src_type) and is waiting for verify
	//newverify:server already send the dynamic password to the new tel(depend on the update_tel_req's new_tel) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTelResp) Reset() {
	*x = UpdateTelResp{}
	mi := &file_api_account_base_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTelResp) ProtoMessage() {}

func (x *UpdateTelResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTelResp.ProtoReflect.Descriptor instead.
func (*UpdateTelResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateTelResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *UpdateTelResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type DelTelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifySrcType string                 `protobuf:"bytes,1,opt,name=verify_src_type,json=verifySrcType,proto3" json:"verify_src_type,omitempty"`
	// when verify_src_type is oauth,this is the oauth service name
	VerifySrcTypeExtra string `protobuf:"bytes,2,opt,name=verify_src_type_extra,json=verifySrcTypeExtra,proto3" json:"verify_src_type_extra,omitempty"`
	// if this is empty,means send dynamic password
	// if this is not empty,means verify dynamic password
	VerifyDynamicPassword string `protobuf:"bytes,3,opt,name=verify_dynamic_password,json=verifyDynamicPassword,proto3" json:"verify_dynamic_password,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DelTelReq) Reset() {
	*x = DelTelReq{}
	mi := &file_api_account_base_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTelReq) ProtoMessage() {}

func (x *DelTelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTelReq.ProtoReflect.Descriptor instead.
func (*DelTelReq) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{37}
}

func (x *DelTelReq) GetVerifySrcType() string {
	if x != nil {
		return x.VerifySrcType
	}
	return ""
}

func (x *DelTelReq) GetVerifySrcTypeExtra() string {
	if x != nil {
		return x.VerifySrcTypeExtra
	}
	return ""
}

func (x *DelTelReq) GetVerifyDynamicPassword() string {
	if x != nil {
		return x.VerifyDynamicPassword
	}
	return ""
}

type DelTelResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//oldverify:server already send the dynamic password to user's email or tel(depend on the del_tel_req's verify_src_type) and is waiting for verify
	//success:nothing need to do
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// if this is true,means this is the last way to login this account
	// if del this,this account will be deleted completely
	Final bool `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	// send dynamic password to where,this will be masked
	// when step is success,ignore this
	Receiver      string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTelResp) Reset() {
	*x = DelTelResp{}
	mi := &file_api_account_base_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTelResp) ProtoMessage() {}

func (x *DelTelResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_base_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTelResp.ProtoReflect.Descriptor instead.
func (*DelTelResp) Descriptor() ([]byte, []int) {
	return file_api_account_base_proto_rawDescGZIP(), []int{38}
}

func (x *DelTelResp) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *DelTelResp) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *DelTelResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

var File_api_account_base_proto protoreflect.FileDescriptor

const file_api_account_base_proto_rawDesc = "" +
	"\n" +
	"\x16api/account_base.proto\x12\aaccount\x1a\x0fpbex/pbex.proto\"\x9c\x02\n" +
	"\tbase_info\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06idcard\x18\x02 \x01(\tR\x06idcard\x12\x10\n" +
	"\x03tel\x18\x03 \x01(\tR\x03tel\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05ctime\x18\x05 \x01(\rR\x05ctime\x12\x1f\n" +
	"\vbind_oauths\x18\x06 \x03(\tR\n" +
	"bindOauths\x123\n" +
	"\x05money\x18\a \x03(\v2\x1d.account.base_info.MoneyEntryR\x05money\x12\x10\n" +
	"\x03ban\x18\b \x01(\tR\x03ban\x1a8\n" +
	"\n" +
	"MoneyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"c\n" +
	"\rbase_info_req\x12@\n" +
	"\bsrc_type\x18\x01 \x01(\tB%ҐN\auser_idҐN\x03telҐN\x05emailҐN\x06idcardR\asrcType\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\"8\n" +
	"\x0ebase_info_resp\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.account.base_infoR\x04info\"\x81\x01\n" +
	"\aban_req\x12@\n" +
	"\bsrc_type\x18\x01 \x01(\tB%ҐN\auser_idҐN\x03telҐN\x05emailҐN\x06idcardR\asrcType\x12\x16\n" +
	"\x03src\x18\x02 \x01(\tB\x04\xf0\x90N\x00R\x03src\x12\x1c\n" +
	"\x06reason\x18\x03 \x01(\tB\x04\xf0\x90N\x00R\x06reason\"\n" +
	"\n" +
	"\bban_resp\"e\n" +
	"\tunban_req\x12@\n" +
	"\bsrc_type\x18\x01 \x01(\tB%ҐN\auser_idҐN\x03telҐN\x05emailҐN\x06idcardR\asrcType\x12\x16\n" +
	"\x03src\x18\x02 \x01(\tB\x04\xf0\x90N\x00R\x03src\"\f\n" +
	"\n" +
	"unban_resp\"M\n" +
	"\x11get_oauth_url_req\x128\n" +
	"\x12oauth_service_name\x18\x01 \x01(\tB\n" +
	"ҐN\x06wechatR\x10oauthServiceName\"&\n" +
	"\x12get_oauth_url_resp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xcf\x01\n" +
	"\tlogin_req\x12>\n" +
	"\bsrc_type\x18\x01 \x01(\tB#ҐN\x03telҐN\x05emailҐN\x06idcardҐN\x05oauthR\asrcType\x12*\n" +
	"\x0esrc_type_extra\x18\x02 \x01(\tB\x04\xf0\x90N\x00R\fsrcTypeExtra\x12:\n" +
	"\rpassword_type\x18\x03 \x01(\tB\x15ҐN\x06staticҐN\adynamicR\fpasswordType\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x80\x01\n" +
	"\n" +
	"login_resp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\vtokenexpire\x18\x02 \x01(\x04R\vtokenexpire\x12&\n" +
	"\x04info\x18\x03 \x01(\v2\x12.account.base_infoR\x04info\x12\x12\n" +
	"\x04step\x18\x04 \x01(\tR\x04step\"\x15\n" +
	"\x13temporary_token_req\"N\n" +
	"\x14temporary_token_resp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\vtokenexpire\x18\x02 \x01(\x04R\vtokenexpire\"\x0f\n" +
	"\rself_info_req\"8\n" +
	"\x0eself_info_resp\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.account.base_infoR\x04info\"\x82\x01\n" +
	"\x1aupdate_static_password_req\x12.\n" +
	"\x13old_static_password\x18\x01 \x01(\tR\x11oldStaticPassword\x124\n" +
	"\x13new_static_password\x18\x02 \x01(\tB\x04\xf8\x90N\n" +
	"R\x11newStaticPassword\"\x1d\n" +
	"\x1bupdate_static_password_resp\"\xc9\x01\n" +
	"\x19reset_static_password_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\"L\n" +
	"\x1areset_static_password_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\":\n" +
	"\x1aidcard_duplicate_check_req\x12\x1c\n" +
	"\x06idcard\x18\x01 \x01(\tB\x04\xf0\x90N\x00R\x06idcard\";\n" +
	"\x1bidcard_duplicate_check_resp\x12\x1c\n" +
	"\tduplicate\x18\x01 \x01(\bR\tduplicate\".\n" +
	"\x0eset_idcard_req\x12\x1c\n" +
	"\x06idcard\x18\x01 \x01(\tB\x04\xf0\x90N\x00R\x06idcard\"\x11\n" +
	"\x0fset_idcard_resp\"\xb2\x02\n" +
	"\x10update_oauth_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\x123\n" +
	"\x16new_oauth_service_name\x18\x04 \x01(\tR\x13newOauthServiceName\x12;\n" +
	"\x1anew_oauth_dynamic_password\x18\x05 \x01(\tR\x17newOauthDynamicPassword\"C\n" +
	"\x11update_oauth_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\"\xf8\x01\n" +
	"\rdel_oauth_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\x129\n" +
	"\x16del_oauth_service_name\x18\x04 \x01(\tB\x04\xf0\x90N\x00R\x13delOauthServiceName\"V\n" +
	"\x0edel_oauth_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\"7\n" +
	"\x19email_duplicate_check_req\x12\x1a\n" +
	"\x05email\x18\x01 \x01(\tB\x04\xf0\x90N\x00R\x05email\":\n" +
	"\x1aemail_duplicate_check_resp\x12\x1c\n" +
	"\tduplicate\x18\x01 \x01(\bR\tduplicate\"\xa0\x02\n" +
	"\x10update_email_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\x12!\n" +
	"\tnew_email\x18\x04 \x01(\tB\x04\xf0\x90N\x00R\bnewEmail\x12;\n" +
	"\x1anew_email_dynamic_password\x18\x05 \x01(\tR\x17newEmailDynamicPassword\"C\n" +
	"\x11update_email_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\"\xbd\x01\n" +
	"\rdel_email_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\"V\n" +
	"\x0edel_email_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\"1\n" +
	"\x17tel_duplicate_check_req\x12\x16\n" +
	"\x03tel\x18\x01 \x01(\tB\x04\xf0\x90N\x00R\x03tel\"8\n" +
	"\x18tel_duplicate_check_resp\x12\x1c\n" +
	"\tduplicate\x18\x01 \x01(\bR\tduplicate\"\x96\x02\n" +
	"\x0eupdate_tel_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\x12\x1d\n" +
	"\anew_tel\x18\x04 \x01(\tB\x04\xf0\x90N\x00R\x06newTel\x127\n" +
	"\x18new_tel_dynamic_password\x18\x05 \x01(\tR\x15newTelDynamicPassword\"A\n" +
	"\x0fupdate_tel_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\"\xbb\x01\n" +
	"\vdel_tel_req\x12A\n" +
	"\x0fverify_src_type\x18\x01 \x01(\tB\x19ҐN\x05emailҐN\x03telҐN\x05oauthR\rverifySrcType\x121\n" +
	"\x15verify_src_type_extra\x18\x02 \x01(\tR\x12verifySrcTypeExtra\x126\n" +
	"\x17verify_dynamic_password\x18\x03 \x01(\tR\x15verifyDynamicPassword\"T\n" +
	"\fdel_tel_resp\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver2\xfa\r\n" +
	"\x04base\x12R\n" +
	"\rget_oauth_url\x12\x1a.account.get_oauth_url_req\x1a\x1b.account.get_oauth_url_resp\"\b\x8a\x9fI\x04post\x12:\n" +
	"\x05login\x12\x12.account.login_req\x1a\x13.account.login_resp\"\b\x8a\x9fI\x04post\x12`\n" +
	"\x0ftemporary_token\x12\x1c.account.temporary_token_req\x1a\x1d.account.temporary_token_resp\"\x10\x8a\x9fI\x03get\x92\x9fI\x05token\x12N\n" +
	"\tself_info\x12\x16.account.self_info_req\x1a\x17.account.self_info_resp\"\x10\x8a\x9fI\x03get\x92\x9fI\x05token\x12h\n" +
	"\tbase_info\x12\x16.account.base_info_req\x1a\x17.account.base_info_resp\"*\x8a\x9fI\x04grpc\x8a\x9fI\x04crpc\x9a\x9fI\taccesskey\xa2\x9fI\taccesskey\x12V\n" +
	"\x03ban\x12\x10.account.ban_req\x1a\x11.account.ban_resp\"*\x8a\x9fI\x04grpc\x8a\x9fI\x04crpc\x9a\x9fI\taccesskey\xa2\x9fI\taccesskey\x12\\\n" +
	"\x05unban\x12\x12.account.unban_req\x1a\x13.account.unban_resp\"*\x8a\x9fI\x04grpc\x8a\x9fI\x04crpc\x9a\x9fI\taccesskey\xa2\x9fI\taccesskey\x12v\n" +
	"\x16update_static_password\x12#.account.update_static_password_req\x1a$.account.update_static_password_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12s\n" +
	"\x15reset_static_password\x12\".account.reset_static_password_req\x1a#.account.reset_static_password_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12v\n" +
	"\x16idcard_duplicate_check\x12#.account.idcard_duplicate_check_req\x1a$.account.idcard_duplicate_check_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12R\n" +
	"\n" +
	"set_idcard\x12\x17.account.set_idcard_req\x1a\x18.account.set_idcard_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12X\n" +
	"\fupdate_oauth\x12\x19.account.update_oauth_req\x1a\x1a.account.update_oauth_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12O\n" +
	"\tdel_oauth\x12\x16.account.del_oauth_req\x1a\x17.account.del_oauth_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12s\n" +
	"\x15email_duplicate_check\x12\".account.email_duplicate_check_req\x1a#.account.email_duplicate_check_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12X\n" +
	"\fupdate_email\x12\x19.account.update_email_req\x1a\x1a.account.update_email_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12O\n" +
	"\tdel_email\x12\x16.account.del_email_req\x1a\x17.account.del_email_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12m\n" +
	"\x13tel_duplicate_check\x12 .account.tel_duplicate_check_req\x1a!.account.tel_duplicate_check_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12R\n" +
	"\n" +
	"update_tel\x12\x17.account.update_tel_req\x1a\x18.account.update_tel_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05token\x12I\n" +
	"\adel_tel\x12\x14.account.del_tel_req\x1a\x15.account.del_tel_resp\"\x11\x8a\x9fI\x04post\x92\x9fI\x05tokenB*Z(github.com/chenjie199234/account/api;apib\x06proto3"

var (
	file_api_account_base_proto_rawDescOnce sync.Once
	file_api_account_base_proto_rawDescData []byte
)

func file_api_account_base_proto_rawDescGZIP() []byte {
	file_api_account_base_proto_rawDescOnce.Do(func() {
		file_api_account_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_account_base_proto_rawDesc), len(file_api_account_base_proto_rawDesc)))
	})
	return file_api_account_base_proto_rawDescData
}

var file_api_account_base_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_account_base_proto_goTypes = []any{
	(*BaseInfo)(nil),                 // 0: account.base_info
	(*BaseInfoReq)(nil),              // 1: account.base_info_req
	(*BaseInfoResp)(nil),             // 2: account.base_info_resp
	(*BanReq)(nil),                   // 3: account.ban_req
	(*BanResp)(nil),                  // 4: account.ban_resp
	(*UnbanReq)(nil),                 // 5: account.unban_req
	(*UnbanResp)(nil),                // 6: account.unban_resp
	(*GetOauthUrlReq)(nil),           // 7: account.get_oauth_url_req
	(*GetOauthUrlResp)(nil),          // 8: account.get_oauth_url_resp
	(*LoginReq)(nil),                 // 9: account.login_req
	(*LoginResp)(nil),                // 10: account.login_resp
	(*TemporaryTokenReq)(nil),        // 11: account.temporary_token_req
	(*TemporaryTokenResp)(nil),       // 12: account.temporary_token_resp
	(*SelfInfoReq)(nil),              // 13: account.self_info_req
	(*SelfInfoResp)(nil),             // 14: account.self_info_resp
	(*UpdateStaticPasswordReq)(nil),  // 15: account.update_static_password_req
	(*UpdateStaticPasswordResp)(nil), // 16: account.update_static_password_resp
	(*ResetStaticPasswordReq)(nil),   // 17: account.reset_static_password_req
	(*ResetStaticPasswordResp)(nil),  // 18: account.reset_static_password_resp
	(*IdcardDuplicateCheckReq)(nil),  // 19: account.idcard_duplicate_check_req
	(*IdcardDuplicateCheckResp)(nil), // 20: account.idcard_duplicate_check_resp
	(*SetIdcardReq)(nil),             // 21: account.set_idcard_req
	(*SetIdcardResp)(nil),            // 22: account.set_idcard_resp
	(*UpdateOauthReq)(nil),           // 23: account.update_oauth_req
	(*UpdateOauthResp)(nil),          // 24: account.update_oauth_resp
	(*DelOauthReq)(nil),              // 25: account.del_oauth_req
	(*DelOauthResp)(nil),             // 26: account.del_oauth_resp
	(*EmailDuplicateCheckReq)(nil),   // 27: account.email_duplicate_check_req
	(*EmailDuplicateCheckResp)(nil),  // 28: account.email_duplicate_check_resp
	(*UpdateEmailReq)(nil),           // 29: account.update_email_req
	(*UpdateEmailResp)(nil),          // 30: account.update_email_resp
	(*DelEmailReq)(nil),              // 31: account.del_email_req
	(*DelEmailResp)(nil),             // 32: account.del_email_resp
	(*TelDuplicateCheckReq)(nil),     // 33: account.tel_duplicate_check_req
	(*TelDuplicateCheckResp)(nil),    // 34: account.tel_duplicate_check_resp
	(*UpdateTelReq)(nil),             // 35: account.update_tel_req
	(*UpdateTelResp)(nil),            // 36: account.update_tel_resp
	(*DelTelReq)(nil),                // 37: account.del_tel_req
	(*DelTelResp)(nil),               // 38: account.del_tel_resp
	nil,                              // 39: account.base_info.MoneyEntry
}
var file_api_account_base_proto_depIdxs = []int32{
	39, // 0: account.base_info.money:type_name -> account.base_info.MoneyEntry
	0,  // 1: account.base_info_resp.info:type_name -> account.base_info
	0,  // 2: account.login_resp.info:type_name -> account.base_info
	0,  // 3: account.self_info_resp.info:type_name -> account.base_info
	7,  // 4: account.base.get_oauth_url:input_type -> account.get_oauth_url_req
	9,  // 5: account.base.login:input_type -> account.login_req
	11, // 6: account.base.temporary_token:input_type -> account.temporary_token_req
	13, // 7: account.base.self_info:input_type -> account.self_info_req
	1,  // 8: account.base.base_info:input_type -> account.base_info_req
	3,  // 9: account.base.ban:input_type -> account.ban_req
	5,  // 10: account.base.unban:input_type -> account.unban_req
	15, // 11: account.base.update_static_password:input_type -> account.update_static_password_req
	17, // 12: account.base.reset_static_password:input_type -> account.reset_static_password_req
	19, // 13: account.base.idcard_duplicate_check:input_type -> account.idcard_duplicate_check_req
	21, // 14: account.base.set_idcard:input_type -> account.set_idcard_req
	23, // 15: account.base.update_oauth:input_type -> account.update_oauth_req
	25, // 16: account.base.del_oauth:input_type -> account.del_oauth_req
	27, // 17: account.base.email_duplicate_check:input_type -> account.email_duplicate_check_req
	29, // 18: account.base.update_email:input_type -> account.update_email_req
	31, // 19: account.base.del_email:input_type -> account.del_email_req
	33, // 20: account.base.tel_duplicate_check:input_type -> account.tel_duplicate_check_req
	35, // 21: account.base.update_tel:input_type -> account.update_tel_req
	37, // 22: account.base.del_tel:input_type -> account.del_tel_req
	8,  // 23: account.base.get_oauth_url:output_type -> account.get_oauth_url_resp
	10, // 24: account.base.login:output_type -> account.login_resp
	12, // 25: account.base.temporary_token:output_type -> account.temporary_token_resp
	14, // 26: account.base.self_info:output_type -> account.self_info_resp
	2,  // 27: account.base.base_info:output_type -> account.base_info_resp
	4,  // 28: account.base.ban:output_type -> account.ban_resp
	6,  // 29: account.base.unban:output_type -> account.unban_resp
	16, // 30: account.base.update_static_password:output_type -> account.update_static_password_resp
	18, // 31: account.base.reset_static_password:output_type -> account.reset_static_password_resp
	20, // 32: account.base.idcard_duplicate_check:output_type -> account.idcard_duplicate_check_resp
	22, // 33: account.base.set_idcard:output_type -> account.set_idcard_resp
	24, // 34: account.base.update_oauth:output_type -> account.update_oauth_resp
	26, // 35: account.base.del_oauth:output_type -> account.del_oauth_resp
	28, // 36: account.base.email_duplicate_check:output_type -> account.email_duplicate_check_resp
	30, // 37: account.base.update_email:output_type -> account.update_email_resp
	32, // 38: account.base.del_email:output_type -> account.del_email_resp
	34, // 39: account.base.tel_duplicate_check:output_type -> account.tel_duplicate_check_resp
	36, // 40: account.base.update_tel:output_type -> account.update_tel_resp
	38, // 41: account.base.del_tel:output_type -> account.del_tel_resp
	23, // [23:42] is the sub-list for method output_type
	4,  // [4:23] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_account_base_proto_init() }
func file_api_account_base_proto_init() {
	if File_api_account_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_account_base_proto_rawDesc), len(file_api_account_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_account_base_proto_goTypes,
		DependencyIndexes: file_api_account_base_proto_depIdxs,
		MessageInfos:      file_api_account_base_proto_msgTypes,
	}.Build()
	File_api_account_base_proto = out.File
	file_api_account_base_proto_goTypes = nil
	file_api_account_base_proto_depIdxs = nil
}
