// Code generated by protoc-gen-go-pbex. DO NOT EDIT.
// version:
// 	protoc-gen-pbex v0.0.140
// 	protoc         v7.34.0
// source: api/account_money.proto

package api

// return empty means pass
func (m *GetMoneyLogsReq) Validate() (errstr string) {
	if m.GetSrcType() != "user_id" && m.GetSrcType() != "tel" && m.GetSrcType() != "email" && m.GetSrcType() != "idcard" {
		return "field: src_type in object: GetMoneyLogsReq check failed"
	}
	if len(m.GetSrc()) == 0 {
		return "field: src in object: GetMoneyLogsReq check failed"
	}
	if m.GetStartTime() == 0 {
		return "field: start_time in object: GetMoneyLogsReq check failed"
	}
	if m.GetEndTime() == 0 {
		return "field: end_time in object: GetMoneyLogsReq check failed"
	}
	if m.GetAction() != "spend" && m.GetAction() != "recharge" && m.GetAction() != "refund" && m.GetAction() != "all" {
		return "field: action in object: GetMoneyLogsReq check failed"
	}
	return ""
}

// return empty means pass
func (m *SelfMoneyLogsReq) Validate() (errstr string) {
	if m.GetStartTime() == 0 {
		return "field: start_time in object: SelfMoneyLogsReq check failed"
	}
	if m.GetEndTime() == 0 {
		return "field: end_time in object: SelfMoneyLogsReq check failed"
	}
	if m.GetAction() != "spend" && m.GetAction() != "recharge" && m.GetAction() != "refund" && m.GetAction() != "all" {
		return "field: action in object: SelfMoneyLogsReq check failed"
	}
	return ""
}
