// Code generated by protoc-gen-go-web. DO NOT EDIT.
// versions:
// 	protoc-gen-go-web v0.0.140
// 	protoc            v7.34.0
// source: api/account_money.proto

package api

import (
	context "context"
	cerror "github.com/chenjie199234/Corelib/cerror"
	metadata "github.com/chenjie199234/Corelib/metadata"
	web "github.com/chenjie199234/Corelib/web"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	io "io"
	slog "log/slog"
	http "net/http"
	strconv "strconv"
	strings "strings"
)

var _WebPathMoneySelfMoneyLogs = "/account.Money/SelfMoneyLogs"

type MoneyWebClient interface {
	SelfMoneyLogs(context.Context, *SelfMoneyLogsReq, http.Header) (*SelfMoneyLogsResp, error)
}

type moneyWebClient struct {
	cc *web.WebClient
}

func NewMoneyWebClient(c *web.WebClient) MoneyWebClient {
	return &moneyWebClient{cc: c}
}

func (c *moneyWebClient) SelfMoneyLogs(ctx context.Context, req *SelfMoneyLogsReq, header http.Header) (*SelfMoneyLogsResp, error) {
	if req == nil {
		return nil, cerror.ErrReq
	}
	if errstr := req.Validate(); errstr != "" {
		slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] request validate failed", slog.String("error", errstr))
		return nil, cerror.ErrReq
	}
	if header == nil {
		header = make(http.Header)
	}
	header.Set("Content-Type", "application/x-protobuf")
	header.Set("Accept", "application/x-protobuf")
	reqd, _ := proto.Marshal(req)
	r, e := c.cc.Post(ctx, _WebPathMoneySelfMoneyLogs, "", header, metadata.GetMetadata(ctx), reqd, nil)
	if e != nil {
		slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] send request failed", slog.String("error", e.Error()))
		return nil, e
	}
	data, e := io.ReadAll(r.Body)
	r.Body.Close()
	if e != nil {
		slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] read response failed", slog.String("error", e.Error()))
		return nil, cerror.Convert(e)
	}
	resp := new(SelfMoneyLogsResp)
	if len(data) == 0 {
		return resp, nil
	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/x-protobuf") {
		if e := proto.Unmarshal(data, resp); e != nil {
			slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] decode response failed", slog.String("error", e.Error()))
			return nil, cerror.ErrResp
		}
	} else if e := protojson.Unmarshal(data, resp); e != nil {
		slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] decode response failed", slog.String("error", e.Error()))
		return nil, cerror.ErrResp
	}
	return resp, nil
}

type MoneyWebServer interface {
	// Context is web.NoStreamServerContext
	SelfMoneyLogs(context.Context, *SelfMoneyLogsReq) (*SelfMoneyLogsResp, error)
}

func _Money_SelfMoneyLogs_WebHandler(handler func(context.Context, *SelfMoneyLogsReq) (*SelfMoneyLogsResp, error)) web.OutsideHandler {
	return func(ctx *web.ServerContext) {
		req := new(SelfMoneyLogsReq)
		if strings.HasPrefix(ctx.GetRequest().Header.Get("Content-Type"), "application/json") {
			data, e := io.ReadAll(ctx.GetRequest().Body)
			if e != nil {
				slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] get body failed", slog.String("error", e.Error()))
				ctx.Abort(e)
				return
			}
			if len(data) > 0 {
				if e := protojson.Unmarshal(data, req); e != nil {
					slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] unmarshal json body failed", slog.String("error", e.Error()))
					ctx.Abort(cerror.ErrReq)
					return
				}
			}
		} else if strings.HasPrefix(ctx.GetRequest().Header.Get("Content-Type"), "application/x-protobuf") {
			data, e := io.ReadAll(ctx.GetRequest().Body)
			if e != nil {
				slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] get body failed", slog.String("error", e.Error()))
				ctx.Abort(e)
				return
			}
			if len(data) > 0 {
				if e := proto.Unmarshal(data, req); e != nil {
					slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] unmarshal proto body failed", slog.String("error", e.Error()))
					ctx.Abort(cerror.ErrReq)
					return
				}
			}
		} else {
			if e := ctx.GetRequest().ParseForm(); e != nil {
				slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] parse form failed", slog.String("error", e.Error()))
				ctx.Abort(cerror.ErrReq)
				return
			}
			// req.SetStartTime()
			if form := ctx.GetRequest().Form.Get("start_time"); len(form) != 0 {
				if num, e := strconv.ParseUint(form, 10, 32); e != nil {
					slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] data format wrong", slog.String("field", "start_time"))
					ctx.Abort(cerror.ErrReq)
					return
				} else {
					req.SetStartTime(uint32(num))
				}
			}
			// req.SetEndTime()
			if form := ctx.GetRequest().Form.Get("end_time"); len(form) != 0 {
				if num, e := strconv.ParseUint(form, 10, 32); e != nil {
					slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] data format wrong", slog.String("field", "end_time"))
					ctx.Abort(cerror.ErrReq)
					return
				} else {
					req.SetEndTime(uint32(num))
				}
			}
			// req.SetPage()
			if form := ctx.GetRequest().Form.Get("page"); len(form) != 0 {
				if num, e := strconv.ParseUint(form, 10, 32); e != nil {
					slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] data format wrong", slog.String("field", "page"))
					ctx.Abort(cerror.ErrReq)
					return
				} else {
					req.SetPage(uint32(num))
				}
			}
			// req.SetAction()
			if form := ctx.GetRequest().Form.Get("action"); len(form) != 0 {
				req.SetAction(form)
			}
		}
		if errstr := req.Validate(); errstr != "" {
			slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] request validate failed", slog.String("error", errstr))
			ctx.Abort(cerror.ErrReq)
			return
		}
		resp, e := handler(ctx, req)
		ee := cerror.Convert(e)
		if ee != nil {
			ctx.Abort(ee)
			return
		}
		if ctx.Responsed() {
			return
		}
		if resp == nil {
			resp = new(SelfMoneyLogsResp)
		}
		if strings.HasPrefix(ctx.GetRequest().Header.Get("Accept"), "application/x-protobuf") {
			ctx.SetResponseHeader("Content-Type", "application/x-protobuf")
			respd, _ := proto.Marshal(resp)
			if _, e := ctx.Write(respd); e != nil {
				slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] send response failed", slog.String("error", e.Error()))
			}
		} else {
			ctx.SetResponseHeader("Content-Type", "application/json")
			respd, _ := protojson.MarshalOptions{UseProtoNames: true, UseEnumNumbers: true}.Marshal(resp)
			if _, e := ctx.Write(respd); e != nil {
				slog.ErrorContext(ctx, "[/account.Money/SelfMoneyLogs] send response failed", slog.String("error", e.Error()))
			}
		}
	}
}
func RegisterMoneyWebServer(router *web.Router, svc MoneyWebServer, allmids map[string]web.OutsideHandler) {
	// avoid lint
	_ = allmids
	{
		requiredMids := []string{"token"}
		mids := make([]web.OutsideHandler, 0, 2)
		for _, v := range requiredMids {
			if mid, ok := allmids[v]; ok {
				mids = append(mids, mid)
			} else {
				panic("missing midware:" + v)
			}
		}
		mids = append(mids, _Money_SelfMoneyLogs_WebHandler(svc.SelfMoneyLogs))
		router.Post(_WebPathMoneySelfMoneyLogs, false, mids...)
	}
}
