// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck


//must use the replacer in JSON.stringify() below:
/*
(key,value)=>{
	if(typeof value === "bigint"){
		return value.toString()
	}else if(value instanceof Map){
		return Object.fromEntries(value)
	}else if(value instanceof Uint8Array){
		let binary=''
		let chunkSize=1024
		for(let i = 0;i<value.length;i+=chunkSize){
			let chunk=value.subarray(i,i+chunkSize)
			binary += String.fromCharCode.apply(null,chunk)
		}
		return window.btoa(binary)
	}
	return value
}
*/
export class DelOauthReq{
	/*if this is in a request,the following rules must be obeyed
		value must in ["email","tel","oauth"]
	*/
	verify_src_type?: string
	//when verify_src_type is oauth,this is the oauth service name
	verify_src_type_extra?: string
	//if this is empty,means send dynamic password
	//if this is not empty,means verify dynamic password
	verify_dynamic_password?: string
	/*if this is in a request,the following rules must be obeyed
		value's length must >0
	*/
	del_oauth_service_name?: string

	constructor(){}

	toJSON():any{
		let copy = Object.assign({},this) as any
		Object.keys(copy).forEach(key=>{
			if(copy[key] === undefined || copy[key] === null){
				delete copy[key]
			}
		})
		return copy
	}
}
