// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck


export class UpdateEmailResp{
	//oldverify:server already send the dynamic password to user's email or tel(depend on the update_email_req's verify_src_type) and is waiting for verify
	//newverify:server already send the dynamic password to the new email(depend on the update_email_req's new_email) and is waiting for verify
	//success:nothing need to do
	step?: string
	//send dynamic password to where,this will be masked
	//when step is success,ignore this
	receiver?: string

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("step" in obj){
			if(typeof obj["step"] != 'string'){
				throw "response parse failed"
			}
			this.step=obj["step"]
		}
		if("receiver" in obj){
			if(typeof obj["receiver"] != 'string'){
				throw "response parse failed"
			}
			this.receiver=obj["receiver"]
		}
	}
}
