// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import {BaseInfo} from './browser_message_account_BaseInfo'

export class LoginResp{
	token?: string
	//Warning!!!Type is uint64,be careful of sign(+)
	tokenexpire?: bigint//unix nano timestamp
	info?: BaseInfo
	//verify:server already send the dynamic password to user's email or tel(depend on the login_req's src_type and src) and is waiting for verify
	//password:login success,but this account is new and it can be setted with a static password(optional)
	//success:nothing need to do
	step?: string

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("token" in obj){
			if(typeof obj["token"] != 'string'){
				throw "response parse failed"
			}
			this.token=obj["token"]
		}
		if("tokenexpire" in obj){
			if(typeof obj["tokenexpire"] != 'string'){
				throw "response parse failed"
			}
			let tmp
			try{tmp=BigInt(obj["tokenexpire"])}catch{throw "response parse failed"}
			this.tokenexpire=tmp
		}
		if("info" in obj){
			if(Object.prototype.toString.call(obj["info"]) != '[object Object]'){
				throw "response parse failed"
			}
			let tmp = new BaseInfo()
			tmp.fromJSON(obj["info"])
			this.info=tmp
		}
		if("step" in obj){
			if(typeof obj["step"] != 'string'){
				throw "response parse failed"
			}
			this.step=obj["step"]
		}
	}
}
