// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {UpdateOauthReq} from './browser_message_account_UpdateOauthReq'
import {UpdateOauthResp} from './browser_message_account_UpdateOauthResp'

const _WebPathBaseUpdateOauth: string ="/account.Base/UpdateOauth";

//timeout's unit is ms,it will be used when > 0
export async function UpdateOauth(baseurl: string,req: UpdateOauthReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|UpdateOauthResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathBaseUpdateOauth,'',opts,UpdateOauthResp)
}
