// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {SetIdcardReq} from './browser_message_account_SetIdcardReq'
import {SetIdcardResp} from './browser_message_account_SetIdcardResp'

const _WebPathBaseSetIdcard: string ="/account.Base/SetIdcard";

//timeout's unit is ms,it will be used when > 0
export async function SetIdcard(baseurl: string,req: SetIdcardReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|SetIdcardResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathBaseSetIdcard,'',opts,SetIdcardResp)
}
