// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {ResetStaticPasswordReq} from './browser_message_account_ResetStaticPasswordReq'
import {ResetStaticPasswordResp} from './browser_message_account_ResetStaticPasswordResp'

const _WebPathBaseResetStaticPassword: string ="/account.Base/ResetStaticPassword";

//timeout's unit is ms,it will be used when > 0
export async function ResetStaticPassword(baseurl: string,req: ResetStaticPasswordReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|ResetStaticPasswordResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathBaseResetStaticPassword,'',opts,ResetStaticPasswordResp)
}
