// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {normal_fetch} from './browser_method_util'
import {SelfInfoReq} from './browser_message_account_SelfInfoReq'
import {SelfInfoResp} from './browser_message_account_SelfInfoResp'

const _WebPathBaseSelfInfo: string ="/account.Base/SelfInfo";

//timeout's unit is ms,it will be used when > 0
export async function SelfInfo(baseurl: string,req: SelfInfoReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|SelfInfoResp>{
	let opts: RequestInit = {method:"GET",headers:h}
	return normal_fetch(timeout,baseurl,_WebPathBaseSelfInfo,req.toFORM(),opts,SelfInfoResp)
}
