// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_money.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {SelfMoneyLogsReq} from './browser_message_account_SelfMoneyLogsReq'
import {SelfMoneyLogsResp} from './browser_message_account_SelfMoneyLogsResp'

const _WebPathMoneySelfMoneyLogs: string ="/account.Money/SelfMoneyLogs";

//timeout's unit is ms,it will be used when > 0
export async function SelfMoneyLogs(baseurl: string,req: SelfMoneyLogsReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|SelfMoneyLogsResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathMoneySelfMoneyLogs,'',opts,SelfMoneyLogsResp)
}
