// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {normal_fetch} from './browser_method_util'
import {GetOauthUrlReq} from './browser_message_account_GetOauthUrlReq'
import {GetOauthUrlResp} from './browser_message_account_GetOauthUrlResp'

const _WebPathBaseGetOauthUrl: string ="/account.Base/GetOauthUrl";

//timeout's unit is ms,it will be used when > 0
export async function GetOauthUrl(baseurl: string,req: GetOauthUrlReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|GetOauthUrlResp>{
	let opts: RequestInit = {method:"GET",headers:h}
	return normal_fetch(timeout,baseurl,_WebPathBaseGetOauthUrl,req.toFORM(),opts,GetOauthUrlResp)
}
