// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck


export class UpdateStaticPasswordResp{

	constructor(){}

	fromJSON(_obj: Record<string,any>):void{
	}
}
