// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck


export class GetOauthUrlResp{
	url?: string

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("url" in obj){
			if(typeof obj["url"] != 'string'){
				throw "response parse failed"
			}
			this.url=obj["url"]
		}
	}
}
