// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck


export class GetOauthUrlReq{
	/*if this is in a request,the following rules must be obeyed
		value must in ["wechat"]
	*/
	oauth_service_name?: string

	constructor(){}

	toFORM():string{
		let query=new Array<string>()
		Object.keys(this).forEach(key=>{
			if(key==="oauth_service_name"){
				if(this[key]!=undefined && this[key]!=null){
					query.push(key+"="+encodeURIComponent(this[key]))
				}
			}
		})
		return query.join('&')
	}
}
