// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck


export class BaseInfo{
	user_id?: string
	idcard?: string
	tel?: string
	email?: string
	//Warning!!!Type is uint32,be careful of sign(+) and overflow
	ctime?: number
	bind_oauths?: Array<string>
	//Warning!!!map's value's type is int32,be careful of sign(+,-) and overflow
	money?: Map<string,number>
	ban?: string//if this is not empty,means this account is banned

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("user_id" in obj){
			if(typeof obj["user_id"] != 'string'){
				throw "response parse failed"
			}
			this.user_id=obj["user_id"]
		}
		if("idcard" in obj){
			if(typeof obj["idcard"] != 'string'){
				throw "response parse failed"
			}
			this.idcard=obj["idcard"]
		}
		if("tel" in obj){
			if(typeof obj["tel"] != 'string'){
				throw "response parse failed"
			}
			this.tel=obj["tel"]
		}
		if("email" in obj){
			if(typeof obj["email"] != 'string'){
				throw "response parse failed"
			}
			this.email=obj["email"]
		}
		if("ctime" in obj){
			if(typeof obj["ctime"] != 'number'){
				throw "response parse failed"
			}
			this.ctime=obj["ctime"]
		}
		if("bind_oauths" in obj){
			if(!Array.isArray(obj["bind_oauths"])){
				throw "response parse failed"
			}
			for(let v of obj["bind_oauths"]){
				if(typeof v != 'string'){
					throw "response parse failed"
				}
			}
			this.bind_oauths=obj["bind_oauths"]
		}
		if("money" in obj){
			if(Object.prototype.toString.call(obj["money"])!="[object Object]"){
				throw "response parse failed"
			}
			this.money=new Map<string,number>()
			Object.entries(obj["money"]).forEach(([key, value]) => {
				if(typeof value != 'number'){
					throw "response parse failed"
				}
				this.money.set(key,value)
			})
		}
		if("ban" in obj){
			if(typeof obj["ban"] != 'string'){
				throw "response parse failed"
			}
			this.ban=obj["ban"]
		}
	}
}
