// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/account_base.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {DelOauthReq} from './browser_message_account_DelOauthReq'
import {DelOauthResp} from './browser_message_account_DelOauthResp'

const _WebPathBaseDelOauth: string ="/account.Base/DelOauth";

//timeout's unit is ms,it will be used when > 0
export async function DelOauth(baseurl: string,req: DelOauthReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|DelOauthResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathBaseDelOauth,'',opts,DelOauthResp)
}
