// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.1
// source: api/money.proto

//this is the proto package name,all proto in this project must use this name as the proto package name

package api

import (
	_ "github.com/chenjie199234/Corelib/pbex"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoneyLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` //spend,recharge,refund
	UniqueId    string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	SrcDst      string `protobuf:"bytes,4,opt,name=src_dst,json=srcDst,proto3" json:"src_dst,omitempty"`
	MoneyType   string `protobuf:"bytes,5,opt,name=money_type,json=moneyType,proto3" json:"money_type,omitempty"`
	MoneyAmount uint64 `protobuf:"varint,6,opt,name=money_amount,json=moneyAmount,proto3" json:"money_amount,omitempty"`
	Ctime       int64  `protobuf:"varint,7,opt,name=ctime,proto3" json:"ctime,omitempty"`
}

func (x *MoneyLog) Reset() {
	*x = MoneyLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyLog) ProtoMessage() {}

func (x *MoneyLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyLog.ProtoReflect.Descriptor instead.
func (*MoneyLog) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{0}
}

func (x *MoneyLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MoneyLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MoneyLog) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *MoneyLog) GetSrcDst() string {
	if x != nil {
		return x.SrcDst
	}
	return ""
}

func (x *MoneyLog) GetMoneyType() string {
	if x != nil {
		return x.MoneyType
	}
	return ""
}

func (x *MoneyLog) GetMoneyAmount() uint64 {
	if x != nil {
		return x.MoneyAmount
	}
	return 0
}

func (x *MoneyLog) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

type GetMoneyLogsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //Mongodb's ObjectId.Hex()
}

func (x *GetMoneyLogsReq) Reset() {
	*x = GetMoneyLogsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoneyLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoneyLogsReq) ProtoMessage() {}

func (x *GetMoneyLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoneyLogsReq.ProtoReflect.Descriptor instead.
func (*GetMoneyLogsReq) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{1}
}

func (x *GetMoneyLogsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMoneyLogsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*MoneyLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *GetMoneyLogsResp) Reset() {
	*x = GetMoneyLogsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoneyLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoneyLogsResp) ProtoMessage() {}

func (x *GetMoneyLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoneyLogsResp.ProtoReflect.Descriptor instead.
func (*GetMoneyLogsResp) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoneyLogsResp) GetLogs() []*MoneyLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type RechargeMoneyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RechargeMoneyReq) Reset() {
	*x = RechargeMoneyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeMoneyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeMoneyReq) ProtoMessage() {}

func (x *RechargeMoneyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeMoneyReq.ProtoReflect.Descriptor instead.
func (*RechargeMoneyReq) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{3}
}

type RechargeMoneyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RechargeMoneyResp) Reset() {
	*x = RechargeMoneyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeMoneyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeMoneyResp) ProtoMessage() {}

func (x *RechargeMoneyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeMoneyResp.ProtoReflect.Descriptor instead.
func (*RechargeMoneyResp) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{4}
}

type SpendMoneyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpendMoneyReq) Reset() {
	*x = SpendMoneyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendMoneyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendMoneyReq) ProtoMessage() {}

func (x *SpendMoneyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendMoneyReq.ProtoReflect.Descriptor instead.
func (*SpendMoneyReq) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{5}
}

type SpendMoneyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpendMoneyResp) Reset() {
	*x = SpendMoneyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendMoneyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendMoneyResp) ProtoMessage() {}

func (x *SpendMoneyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendMoneyResp.ProtoReflect.Descriptor instead.
func (*SpendMoneyResp) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{6}
}

type RefundMoneyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefundMoneyReq) Reset() {
	*x = RefundMoneyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundMoneyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundMoneyReq) ProtoMessage() {}

func (x *RefundMoneyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundMoneyReq.ProtoReflect.Descriptor instead.
func (*RefundMoneyReq) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{7}
}

type RefundMoneyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefundMoneyResp) Reset() {
	*x = RefundMoneyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_money_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundMoneyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundMoneyResp) ProtoMessage() {}

func (x *RefundMoneyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_money_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundMoneyResp.ProtoReflect.Descriptor instead.
func (*RefundMoneyResp) Descriptor() ([]byte, []int) {
	return file_api_money_proto_rawDescGZIP(), []int{8}
}

var File_api_money_proto protoreflect.FileDescriptor

var file_api_money_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x0f, 0x70, 0x62, 0x65, 0x78,
	0x2f, 0x70, 0x62, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x09,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x5f, 0x64,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x72, 0x63, 0x44, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x5f,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x04, 0xe0, 0x90, 0x4e, 0x18, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a,
	0x13, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x14, 0x0a, 0x12,
	0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72,
	0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22, 0x11, 0x0a, 0x0f, 0x73, 0x70, 0x65,
	0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x22, 0x12, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x5f, 0x72, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x32, 0xbe, 0x02, 0x0a, 0x05, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x5d, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x67, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x72,
	0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x67, 0x65, 0x74,
	0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x22, 0x10, 0x8a, 0x9f, 0x49, 0x03, 0x67, 0x65, 0x74, 0x92, 0x9f, 0x49, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x4b, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x72,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65,
	0x71, 0x1a, 0x1c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12,
	0x42, 0x0a, 0x0b, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x18,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x72, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x65, 0x6e, 0x6a, 0x69, 0x65,
	0x31, 0x39, 0x39, 0x32, 0x33, 0x34, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_money_proto_rawDescOnce sync.Once
	file_api_money_proto_rawDescData = file_api_money_proto_rawDesc
)

func file_api_money_proto_rawDescGZIP() []byte {
	file_api_money_proto_rawDescOnce.Do(func() {
		file_api_money_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_money_proto_rawDescData)
	})
	return file_api_money_proto_rawDescData
}

var file_api_money_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_money_proto_goTypes = []interface{}{
	(*MoneyLog)(nil),          // 0: account.money_log
	(*GetMoneyLogsReq)(nil),   // 1: account.get_money_logs_req
	(*GetMoneyLogsResp)(nil),  // 2: account.get_money_logs_resp
	(*RechargeMoneyReq)(nil),  // 3: account.recharge_money_req
	(*RechargeMoneyResp)(nil), // 4: account.recharge_money_resp
	(*SpendMoneyReq)(nil),     // 5: account.spend_money_req
	(*SpendMoneyResp)(nil),    // 6: account.spend_money_resp
	(*RefundMoneyReq)(nil),    // 7: account.refund_money_req
	(*RefundMoneyResp)(nil),   // 8: account.refund_money_resp
}
var file_api_money_proto_depIdxs = []int32{
	0, // 0: account.get_money_logs_resp.logs:type_name -> account.money_log
	1, // 1: account.money.get_money_logs:input_type -> account.get_money_logs_req
	3, // 2: account.money.recharge_money:input_type -> account.recharge_money_req
	5, // 3: account.money.spend_money:input_type -> account.spend_money_req
	7, // 4: account.money.refund_money:input_type -> account.refund_money_req
	2, // 5: account.money.get_money_logs:output_type -> account.get_money_logs_resp
	4, // 6: account.money.recharge_money:output_type -> account.recharge_money_resp
	6, // 7: account.money.spend_money:output_type -> account.spend_money_resp
	8, // 8: account.money.refund_money:output_type -> account.refund_money_resp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_money_proto_init() }
func file_api_money_proto_init() {
	if File_api_money_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_money_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoneyLogsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoneyLogsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeMoneyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeMoneyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendMoneyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendMoneyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundMoneyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_money_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundMoneyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_money_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_money_proto_goTypes,
		DependencyIndexes: file_api_money_proto_depIdxs,
		MessageInfos:      file_api_money_proto_msgTypes,
	}.Build()
	File_api_money_proto = out.File
	file_api_money_proto_rawDesc = nil
	file_api_money_proto_goTypes = nil
	file_api_money_proto_depIdxs = nil
}
