// Code generated by protoc-gen-go-pbex. DO NOT EDIT.
// version:
// 	protoc-gen-pbex v0.0.77
// 	protoc         v4.24.1
// source: api/money.proto

package api

// return empty means pass
func (m *GetMoneyLogsReq) Validate() (errstr string) {
	if len(m.GetUserId()) != 24 {
		return "field: user_id in object: get_money_logs_req check value str len eq failed"
	}
	return ""
}
